#[derive(Clone, PartialEq)]
pub enum HTMLTag {
    A,
    Abbr,
    Address,
    Area,
    Article,
    Aside,
    Audio,
    B,
    Base,
    Bdi,
    Bdo,
    Blockquote,
    Body,
    Br,
    Button,
    Canvas,
    Caption,
    Cite,
    Code,
    Col,
    Colgroup,
    Data,
    Datalist,
    Dd,
    Del,
    Details,
    Dfn,
    Dialog,
    Div,
    Dl,
    Dt,
    Em,
    Embed,
    Fieldset,
    Figcaption,
    Figure,
    Footer,
    Form,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Head,
    Header,
    Hr,
    Html,
    I,
    Iframe,
    Img,
    Input,
    Ins,
    Kbd,
    Label,
    Legend,
    Li,
    Link,
    Main,
    Map,
    Mark,
    Meta,
    Meter,
    Nav,
    Noscript,
    Object,
    Ol,
    Optgroup,
    Option,
    Output,
    P,
    Param,
    Picture,
    Pre,
    Progress,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Script,
    Section,
    Select,
    Slot,
    Small,
    Source,
    Span,
    Strong,
    Style,
    Sub,
    Summary,
    Sup,
    Svg,
    Table,
    Tbody,
    Td,
    Template,
    Textarea,
    Tfoot,
    Th,
    Thead,
    Time,
    Title,
    Tr,
    Track,
    U,
    Ul,
    Var,
    Video,
    Wbr,
}

pub fn get_html_tag(tag: &HTMLTag) -> String {
    match tag {
        HTMLTag::A => String::from("a"),
        HTMLTag::Abbr => String::from("abbr"),
        HTMLTag::Address => String::from("address"),
        HTMLTag::Area => String::from("area"),
        HTMLTag::Article => String::from("article"),
        HTMLTag::Aside => String::from("aside"),
        HTMLTag::Audio => String::from("audio"),
        HTMLTag::B => String::from("b"),
        HTMLTag::Base => String::from("base"),
        HTMLTag::Bdi => String::from("bdi"),
        HTMLTag::Bdo => String::from("bdo"),
        HTMLTag::Blockquote => String::from("blockquote"),
        HTMLTag::Body => String::from("body"),
        HTMLTag::Br => String::from("br"),
        HTMLTag::Button => String::from("button"),
        HTMLTag::Canvas => String::from("canvas"),
        HTMLTag::Caption => String::from("caption"),
        HTMLTag::Cite => String::from("cite"),
        HTMLTag::Code => String::from("code"),
        HTMLTag::Col => String::from("col"),
        HTMLTag::Colgroup => String::from("colgroup"),
        HTMLTag::Data => String::from("data"),
        HTMLTag::Datalist => String::from("datalist"),
        HTMLTag::Dd => String::from("dd"),
        HTMLTag::Del => String::from("del"),
        HTMLTag::Details => String::from("details"),
        HTMLTag::Dfn => String::from("dfn"),
        HTMLTag::Dialog => String::from("dialog"),
        HTMLTag::Div => String::from("div"),
        HTMLTag::Dl => String::from("dl"),
        HTMLTag::Dt => String::from("dt"),
        HTMLTag::Em => String::from("em"),
        HTMLTag::Embed => String::from("embed"),
        HTMLTag::Fieldset => String::from("fieldset"),
        HTMLTag::Figcaption => String::from("figcaption"),
        HTMLTag::Figure => String::from("figure"),
        HTMLTag::Footer => String::from("footer"),
        HTMLTag::Form => String::from("form"),
        HTMLTag::H1 => String::from("h1"),
        HTMLTag::H2 => String::from("h2"),
        HTMLTag::H3 => String::from("h3"),
        HTMLTag::H4 => String::from("h4"),
        HTMLTag::H5 => String::from("h5"),
        HTMLTag::H6 => String::from("h6"),
        HTMLTag::Head => String::from("head"),
        HTMLTag::Header => String::from("header"),
        HTMLTag::Hr => String::from("hr"),
        HTMLTag::Html => String::from("html"),
        HTMLTag::I => String::from("i"),
        HTMLTag::Iframe => String::from("iframe"),
        HTMLTag::Img => String::from("img"),
        HTMLTag::Input => String::from("input"),
        HTMLTag::Ins => String::from("ins"),
        HTMLTag::Kbd => String::from("kbd"),
        HTMLTag::Label => String::from("label"),
        HTMLTag::Legend => String::from("legend"),
        HTMLTag::Li => String::from("li"),
        HTMLTag::Link => String::from("link"),
        HTMLTag::Main => String::from("main"),
        HTMLTag::Map => String::from("map"),
        HTMLTag::Mark => String::from("mark"),
        HTMLTag::Meta => String::from("meta"),
        HTMLTag::Meter => String::from("meter"),
        HTMLTag::Nav => String::from("nav"),
        HTMLTag::Noscript => String::from("noscript"),
        HTMLTag::Object => String::from("object"),
        HTMLTag::Ol => String::from("ol"),
        HTMLTag::Optgroup => String::from("optgroup"),
        HTMLTag::Option => String::from("option"),
        HTMLTag::Output => String::from("output"),
        HTMLTag::P => String::from("p"),
        HTMLTag::Param => String::from("param"),
        HTMLTag::Picture => String::from("picture"),
        HTMLTag::Pre => String::from("pre"),
        HTMLTag::Progress => String::from("progress"),
        HTMLTag::Q => String::from("q"),
        HTMLTag::Rp => String::from("rp"),
        HTMLTag::Rt => String::from("rt"),
        HTMLTag::Ruby => String::from("ruby"),
        HTMLTag::S => String::from("s"),
        HTMLTag::Samp => String::from("samp"),
        HTMLTag::Script => String::from("script"),
        HTMLTag::Section => String::from("section"),
        HTMLTag::Select => String::from("select"),
        HTMLTag::Slot => String::from("slot"),
        HTMLTag::Small => String::from("small"),
        HTMLTag::Source => String::from("source"),
        HTMLTag::Span => String::from("span"),
        HTMLTag::Strong => String::from("strong"),
        HTMLTag::Style => String::from("style"),
        HTMLTag::Sub => String::from("sub"),
        HTMLTag::Summary => String::from("summary"),
        HTMLTag::Sup => String::from("sup"),
        HTMLTag::Svg => String::from("svg"),
        HTMLTag::Table => String::from("table"),
        HTMLTag::Tbody => String::from("tbody"),
        HTMLTag::Td => String::from("td"),
        HTMLTag::Template => String::from("template"),
        HTMLTag::Textarea => String::from("textarea"),
        HTMLTag::Tfoot => String::from("tfoot"),
        HTMLTag::Th => String::from("th"),
        HTMLTag::Thead => String::from("thead"),
        HTMLTag::Time => String::from("time"),
        HTMLTag::Title => String::from("title"),
        HTMLTag::Tr => String::from("tr"),
        HTMLTag::Track => String::from("track"),
        HTMLTag::U => String::from("u"),
        HTMLTag::Ul => String::from("ul"),
        HTMLTag::Var => String::from("var"),
        HTMLTag::Video => String::from("video"),
        HTMLTag::Wbr => String::from("wbr"),
    }
}
